language:  generic
sudo:      required
services:
    -docker


before_install:
    -docker build -t frontend:dev -f Dockerfile.dev .

script:
    -docker -e CI=true run frontend:dev npm run test -- --coverage